# Generated by Django 4.0.1 on 2022-04-12 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_name', models.CharField(max_length=100)),
                ('email_subject', models.CharField(max_length=300)),
                ('email_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackerHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_date', models.DateTimeField()),
                ('tracker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.tracker')),
            ],
        ),
    ]
