# Generated by Django 4.0.1 on 2022-04-15 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bloop',
        ),
        migrations.AlterField(
            model_name='trackerhit',
            name='hit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
