# Generated by Django 4.0.1 on 2022-04-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_delete_bloop_alter_trackerhit_hit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerhit',
            name='ip',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
